Добавляет наставника
htmlacademy-htmlcss/2064221-sedona-35 pull request #1
Opened 2022-09-20 09:54 UTC by ElviraFedchenko

2022-09-20 13:41 UTC, GennadiyM requested changes

2022-09-20 13:41 UTC, GennadiyM commented on Readme.md
> +* Наставник: `Геннадий Максимов` (https://htmlacademy.ru/profile/gennadiy).
Ну фактически правильно. Надо было прям как у вас сделать. Обратите внимние, что когда заходите в гит то эта информация (ваше имя фамилия) превращаются в ссылку.  https://github.com/htmlacademy-htmlcss/2064221-sedona-35 вот тоже самое должно произойти и с информацией обо мне. А для этого нужно записать конструкцию []() где в квадратных скобках название ссылки, в круглых ссылка

2022-09-21 07:02 UTC, ElviraFedchenko commented on Readme.md
> +* Наставник: `Геннадий Максимов` (https://htmlacademy.ru/profile/gennadiy).
я поняла, спасибо. исправила!

2022-09-22 10:01 UTC, GennadiyM approved these changes

2022-09-22 10:13 UTC, merged

2022-10-11 07:39 UTC, ElviraFedchenko commented
внесла изменения, проверьте

вт, 20 сент. 2022 г. в 16:41, GennadiyM ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Readme.md
> <https://github.com/htmlacademy-htmlcss/2064221-sedona-35/pull/1#discussion_r975379634>
> :
>
> > @@ -1,7 +1,7 @@
>  # Личный проект «Седона»
>
>  * Студент: [Эльвира Федченко](https://up.htmlacademy.ru/htmlcss/35/user/2064221).
> -* Наставник: `Неизвестно`.
> +* Наставник: `Геннадий Максимов` (https://htmlacademy.ru/profile/gennadiy).
>
> Ну фактически правильно. Надо было прям как у вас сделать. Обратите
> внимние, что когда заходите в гит то эта информация (ваше имя фамилия)
> превращаются в ссылку.
> https://github.com/htmlacademy-htmlcss/2064221-sedona-35 вот тоже самое
> должно произойти и с информацией обо мне. А для этого нужно записать
> конструкцию где в квадратных скобках название ссылки, в круглых ссылка
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/htmlacademy-htmlcss/2064221-sedona-35/pull/1#pullrequestreview-1113843953>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3FQEKTIKHM7SAA3O6G6D6TV7G5HZANCNFSM6AAAAAAQQ4X33M>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>